# Generated by Django 4.1 on 2022-08-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stnodueapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('department', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('conpassword', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
    ]
