# Generated by Django 4.1 on 2022-08-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stnodueapp', '0003_hallticket_lib_sp_tc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lib',
            new_name='library',
        ),
        migrations.RenameModel(
            old_name='sp',
            new_name='sports',
        ),
        migrations.AlterModelTable(
            name='library',
            table='library',
        ),
        migrations.AlterModelTable(
            name='sports',
            table='sports',
        ),
    ]
