# Generated by Django 4.0.5 on 2022-08-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stnodueapp', '0004_rename_lib_library_rename_sp_sports_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='library',
            new_name='librarydb',
        ),
        migrations.RenameModel(
            old_name='sports',
            new_name='sportsdb',
        ),
        migrations.AlterModelTable(
            name='librarydb',
            table='librarydb',
        ),
        migrations.AlterModelTable(
            name='sportsdb',
            table='sportsdb',
        ),
    ]
