# Generated by Django 4.1 on 2022-09-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stnodueapp', '0005_rename_library_librarydb_rename_sports_sportsdb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
    ]
