# Generated by Django 4.1 on 2022-09-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stnodueapp', '0006_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='tc_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('addate', models.DateField()),
                ('course', models.CharField(max_length=10)),
                ('dateofapply', models.DateField(auto_now=True)),
                ('noduereasons', models.CharField(max_length=100)),
                ('accounts', models.CharField(default=None, max_length=20, null=True)),
                ('accountsremark', models.CharField(default=None, max_length=200, null=True)),
                ('hod', models.CharField(default=None, max_length=20, null=True)),
                ('hodremark', models.CharField(default=None, max_length=200, null=True)),
                ('admin', models.CharField(default=None, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tc_db',
            },
        ),
    ]
