# Generated by Django 4.1 on 2022-09-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stnodueapp', '0008_alter_tc_db_addate_alter_tc_db_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_db',
            name='addate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tc_db',
            name='dob',
            field=models.DateField(),
        ),
    ]
