# Generated by Django 4.1 on 2022-09-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stnodueapp', '0010_alter_tc_db_addate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_db',
            name='addate',
            field=models.DateField(),
        ),
    ]
