# Generated by Django 4.1 on 2022-09-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stnodueapp', '0011_alter_tc_db_addate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='regno',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
